# This is a basic workflow to help you get started with Actions

name: Update Server

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Restart server
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://www.faithy3.moe/restart2007.php'
          method: 'POST'
          username: ${{ secrets.UPDATE_USER }}
          password: ${{ secrets.UPDATE_KEY }}
